import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(),
  routes: [
    {
      path: '/',
      redirect: '/fields',
    },
    {
      path: '/fields',
      name: 'field-list',
      component: () => import('@/views/FieldList.vue'),
      meta: { title: '字段管理' },
    },
    {
      path: '/fields/create',
      name: 'field-create',
      component: () => import('@/views/FieldForm.vue'),
      meta: { title: '新建字段', isCreate: true },
    },
    {
      path: '/fields/:id/view',
      name: 'field-view',
      component: () => import('@/views/FieldForm.vue'),
      meta: { title: '查看字段', isCreate: false, isView: true },
    },
    {
      path: '/fields/:id/edit',
      name: 'field-edit',
      component: () => import('@/views/FieldForm.vue'),
      meta: { title: '编辑字段', isCreate: false },
    },
    {
      path: '/npcs',
      name: 'npc-list',
      component: () => import('@/views/NPCList.vue'),
      meta: { title: 'NPC 管理' },
    },
    {
      path: '/npcs/create',
      name: 'npc-create',
      component: () => import('@/views/NPCForm.vue'),
      props: { mode: 'create' },
      meta: { title: '新建 NPC' },
    },
    {
      path: '/npcs/:id/view',
      name: 'npc-view',
      component: () => import('@/views/NPCForm.vue'),
      props: (route) => ({ mode: 'view', id: Number(route.params.id) }),
      meta: { title: '查看 NPC' },
    },
    {
      path: '/npcs/:id/edit',
      name: 'npc-edit',
      component: () => import('@/views/NPCForm.vue'),
      props: (route) => ({ mode: 'edit', id: Number(route.params.id) }),
      meta: { title: '编辑 NPC' },
    },
    {
      path: '/templates',
      name: 'template-list',
      component: () => import('@/views/TemplateList.vue'),
      meta: { title: '模板管理' },
    },
    {
      path: '/templates/create',
      name: 'template-create',
      component: () => import('@/views/TemplateForm.vue'),
      props: { mode: 'create' },
      meta: { title: '新建模板' },
    },
    {
      path: '/templates/:id/view',
      name: 'template-view',
      component: () => import('@/views/TemplateForm.vue'),
      props: (route) => ({ mode: 'view', id: Number(route.params.id) }),
      meta: { title: '查看模板' },
    },
    {
      path: '/templates/:id/edit',
      name: 'template-edit',
      component: () => import('@/views/TemplateForm.vue'),
      props: (route) => ({ mode: 'edit', id: Number(route.params.id) }),
      meta: { title: '编辑模板' },
    },
    {
      path: '/runtime-bb-keys',
      name: 'runtime-bb-key-list',
      component: () => import('@/views/RuntimeBbKeyList.vue'),
      meta: { title: '运行时 BB Key 管理' },
    },
    {
      path: '/runtime-bb-keys/create',
      name: 'runtime-bb-key-create',
      component: () => import('@/views/RuntimeBbKeyForm.vue'),
      meta: { title: '新建运行时 Key', isCreate: true },
    },
    {
      path: '/runtime-bb-keys/:id/view',
      name: 'runtime-bb-key-view',
      component: () => import('@/views/RuntimeBbKeyForm.vue'),
      meta: { title: '查看运行时 Key', isCreate: false, isView: true },
    },
    {
      path: '/runtime-bb-keys/:id/edit',
      name: 'runtime-bb-key-edit',
      component: () => import('@/views/RuntimeBbKeyForm.vue'),
      meta: { title: '编辑运行时 Key', isCreate: false },
    },
    {
      path: '/event-types',
      name: 'event-type-list',
      component: () => import('@/views/EventTypeList.vue'),
      meta: { title: '事件类型管理' },
    },
    {
      path: '/event-types/create',
      name: 'event-type-create',
      component: () => import('@/views/EventTypeForm.vue'),
      meta: { title: '新建事件类型', isCreate: true },
    },
    {
      path: '/event-types/:id/view',
      name: 'event-type-view',
      component: () => import('@/views/EventTypeForm.vue'),
      meta: { title: '查看事件类型', isCreate: false, isView: true },
    },
    {
      path: '/event-types/:id/edit',
      name: 'event-type-edit',
      component: () => import('@/views/EventTypeForm.vue'),
      meta: { title: '编辑事件类型', isCreate: false },
    },
    {
      path: '/event-type-schemas',
      name: 'event-type-schema-list',
      component: () => import('@/views/EventTypeSchemaList.vue'),
      meta: { title: '扩展字段管理' },
    },
    {
      path: '/event-type-schemas/create',
      name: 'event-type-schema-create',
      component: () => import('@/views/EventTypeSchemaForm.vue'),
      meta: { title: '新建扩展字段', isCreate: true },
    },
    {
      path: '/event-type-schemas/:id/view',
      name: 'event-type-schema-view',
      component: () => import('@/views/EventTypeSchemaForm.vue'),
      meta: { title: '查看扩展字段', isCreate: false, isView: true },
    },
    {
      path: '/event-type-schemas/:id/edit',
      name: 'event-type-schema-edit',
      component: () => import('@/views/EventTypeSchemaForm.vue'),
      meta: { title: '编辑扩展字段', isCreate: false },
    },
    {
      path: '/fsm-state-dicts',
      name: 'fsm-state-dict-list',
      component: () => import('@/views/FsmStateDictList.vue'),
      meta: { title: '状态字典' },
    },
    {
      path: '/fsm-state-dicts/create',
      name: 'fsm-state-dict-create',
      component: () => import('@/views/FsmStateDictForm.vue'),
      meta: { title: '新建状态', isCreate: true },
    },
    {
      path: '/fsm-state-dicts/:id/view',
      name: 'fsm-state-dict-view',
      component: () => import('@/views/FsmStateDictForm.vue'),
      meta: { title: '查看状态', isCreate: false, isView: true },
    },
    {
      path: '/fsm-state-dicts/:id/edit',
      name: 'fsm-state-dict-edit',
      component: () => import('@/views/FsmStateDictForm.vue'),
      meta: { title: '编辑状态', isCreate: false },
    },
    {
      path: '/fsm-configs',
      name: 'fsm-config-list',
      component: () => import('@/views/FsmConfigList.vue'),
      meta: { title: '状态机管理' },
    },
    {
      path: '/fsm-configs/create',
      name: 'fsm-config-create',
      component: () => import('@/views/FsmConfigForm.vue'),
      meta: { title: '新建状态机', isCreate: true },
    },
    {
      path: '/fsm-configs/:id/view',
      name: 'fsm-config-view',
      component: () => import('@/views/FsmConfigForm.vue'),
      meta: { title: '查看状态机', isCreate: false, isView: true },
    },
    {
      path: '/fsm-configs/:id/edit',
      name: 'fsm-config-edit',
      component: () => import('@/views/FsmConfigForm.vue'),
      meta: { title: '编辑状态机', isCreate: false },
    },
    {
      path: '/bt-trees',
      name: 'bt-tree-list',
      component: () => import('@/views/BtTreeList.vue'),
      meta: { title: '行为树管理' },
    },
    {
      path: '/bt-trees/create',
      name: 'bt-tree-create',
      component: () => import('@/views/BtTreeForm.vue'),
      meta: { title: '新建行为树', isCreate: true, isView: false },
    },
    {
      path: '/bt-trees/:id/view',
      name: 'bt-tree-view',
      component: () => import('@/views/BtTreeForm.vue'),
      meta: { title: '查看行为树', isCreate: false, isView: true },
    },
    {
      path: '/bt-trees/:id/edit',
      name: 'bt-tree-edit',
      component: () => import('@/views/BtTreeForm.vue'),
      meta: { title: '编辑行为树', isCreate: false, isView: false },
    },
    // ── 节点类型管理（已隐藏，内置节点由 seed 管理，无需前端页面）──
    // {
    //   path: '/bt-node-types',
    //   name: 'bt-node-type-list',
    //   component: () => import('@/views/BtNodeTypeList.vue'),
    //   meta: { title: '节点类型管理' },
    // },
    // {
    //   path: '/bt-node-types/create',
    //   name: 'bt-node-type-create',
    //   component: () => import('@/views/BtNodeTypeForm.vue'),
    //   meta: { title: '新建节点类型', isCreate: true, isView: false },
    // },
    // {
    //   path: '/bt-node-types/:id/view',
    //   name: 'bt-node-type-view',
    //   component: () => import('@/views/BtNodeTypeForm.vue'),
    //   meta: { title: '查看节点类型', isCreate: false, isView: true },
    // },
    // {
    //   path: '/bt-node-types/:id/edit',
    //   name: 'bt-node-type-edit',
    //   component: () => import('@/views/BtNodeTypeForm.vue'),
    //   meta: { title: '编辑节点类型', isCreate: false, isView: false },
    // },
    {
      path: '/:pathMatch(.*)*',
      name: 'not-found',
      component: () => import('@/views/NotFound.vue'),
      meta: { title: '页面不存在' },
    },
  ],
})

export default router
